version: '3.7'

services:
  db-slave1-fwd:
    image: mariadb:10.5
    container_name: db-slave1-fwd
    volumes:
      - ./slave1.cnf:/etc/mysql/conf.d/repl.cnf
      - ./slave.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      slave1-fwd-network:
        ipv4_address: 192.168.128.4

networks:
  slave1-fwd-network:
    name: forwarder-network