version: '3.7'

services:
  db-slave1-merch:
    image: mariadb:10.5
    container_name: db-slave1-merch
    volumes:
      - ./slave1.cnf:/etc/mysql/conf.d/repl.cnf
      - ./slave.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3302:3306"
    networks:
      slave1-merch-network:
        ipv4_address: 192.168.96.4

networks:
  slave1-merch-network:
    name: merchant-network