version: '3.7'

services:
  mysqlmaster:
    image: mariadb:10.5
    container_name: db-master-merch
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/repl.cnf
      - ./master.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: crypto_db
      MYSQL_USER: crypto_user
      MYSQL_PASSWORD: cryptopassword
    ports:
      - "3301:3306"
    networks:
      merchant-network:
        ipv4_address: 192.168.96.3

networks:
  merchant-network:
    name: merchant-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/20
          gateway: 192.168.96.1
