version: '3.7'

services:
  db-slave2-fwd:
    image: mariadb:10.5
    container_name: db-slave2-fwd
    volumes:
      - ./slave2.cnf:/etc/mysql/conf.d/repl.cnf
      - ./slave.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3308:3306"
    networks:
      slave2-fwd-network:
        ipv4_address: 192.168.128.5

networks:
  slave2-fwd-network:
    name: forwarder-network