version: '3.7'

services:
  mon-merch:
    build:
      context: ../monitor/
    container_name: mon-merch
    env_file:
      - .env
    networks:
      mon-merch-network:
        ipv4_address: 192.168.96.200

networks:
  mon-merch-network:
    name: merchant-network
