version: '3.7'

services:
  mon-merch:
    build:
      context: ../monitor/
    container_name: mon-merch
    command: python ping.py 192.168.96.3 192.168.96.4 192.168.96.5
    env_file:
      - .env
    networks:
      mon-merch-network:
        ipv4_address: 192.168.96.200

networks:
  mon-merch-network:
    name: merchant-network
