version: '3.7'

services:
  mon-fwd:
    build:
      context: ../monitor/
    container_name: mon-fwd
    command: python ping.py 192.168.128.3 192.168.128.4 192.168.128.5
    env_file:
      - .env
    networks:
      mon-fwd-network:
        ipv4_address: 192.168.128.200

networks:
  mon-fwd-network:
    name: crypto-network
