version: '3.7'

services:
  db-master-fwd:
    image: mariadb:10.5
    container_name: db-master-fwd
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/repl.cnf
      - ./master.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    networks:
      forwarder-network:
        ipv4_address: 192.168.128.3

networks:
  forwarder-network:
    name: forwarder-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.128.0/20
        gateway: 192.168.128.1
