version: '3.7'

services:
  proxysql-fwd:
    image: proxysql/proxysql
    container_name: proxysql-fwd
    ports:
      - '16032:6032'
      - '16033:6033'
      - '16070:6070'
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    networks:
      proxysql-fwd-network:
        ipv4_address: 192.168.128.2

networks:
  proxysql-fwd-network:
    name: forwarder-network
